version: '3.1'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'

  api:
    build: ./api
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app
    depends_on:
      - postgres
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - api
