# Generated by Django 4.1 on 2022-08-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('webpage', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
