# Generated by Django 4.1 on 2022-08-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programm',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
