# Generated by Django 4.1 on 2022-08-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='programm',
            name='link',
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('fieldType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fieldtype')),
                ('programmId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.programm')),
            ],
        ),
    ]
