# Generated by Django 4.1 on 2022-08-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fieldtype_remove_programm_link_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='fieldType',
            new_name='field_type',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='programmId',
            new_name='programm',
        ),
    ]
